
config_folder: './content'

posts_folder: 'posts'
pages_folder: 'pages'
static_folder: 'static'

templates_folder: 'templates'
partials_folder: 'partials'

# https://docs.python.org/3.7/library/datetime.html#strftime-and-strptime-behavior
post_date_display_format: '%b %d, %Y'



output_folder: 'DONE_SITE'

posts_slug: 'posts'
topics_slug: 'topics'

archive_out_title: 'Blog'
archive_out_slug: 'blog.html'

site_name: 'alexnotes.xyz'

tabs:
  - - 'About'
    - '/'
  - - 'Reading'
    - '/reading.html'
  - - 'Blog'
    - '/blog.html'
  - - 'Portfolio'
    - '/portfolio.html'
